name: HUGO Github Action

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with: # 参数
          submodules: true

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --gc --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: jerry011235/jerry011235.github.io
          publish_branch: main
          publish_dir: ./public
